# Imports

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


data = pd.read_csv(r'dataset/medical_students_dataset.csv')

# EDA

In [3]:
data.head()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,NaN,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  str
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  str
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  str
 12  Smoking         180000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB

There are at last 20,000 rows with null values, could be more

In [5]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Student ID,180000.0,49974.042078,28879.641657,1.000000,24971.750000,49943.500000,74986.000000,100000.000000
Age,180000.0,26.021561,4.890528,18.000000,22.000000,26.000000,30.000000,34.000000
Height,180000.0,174.947103,14.447560,150.000041,162.476110,174.899914,187.464417,199.998639
Weight,180000.0,69.971585,17.322574,40.000578,54.969838,69.979384,84.980097,99.999907
BMI,180000.0,23.338869,7.033554,10.074837,17.858396,22.671401,27.997487,44.355113
Temperature,180000.0,98.600948,0.500530,96.397835,98.264750,98.599654,98.940543,100.824857
Heart Rate,180000.0,79.503767,11.540755,60.000000,70.000000,80.000000,90.000000,99.000000
Blood Pressure,180000.0,114.558033,14.403353,90.000000,102.000000,115.000000,127.000000,139.000000
Cholesterol,180000.0,184.486361,37.559678,120.000000,152.000000,184.000000,217.000000,249.000000

In [7]:
data.isnull().sum()

Student ID        20000
Age               20000
Gender            20000
Height            20000
Weight            20000
Blood Type        20000
BMI               20000
Temperature       20000
Heart Rate        20000
Blood Pressure    20000
Cholesterol       20000
Diabetes          20000
Smoking           20000
dtype: int64

From our EDA, we can see that there are a lot of missing/null values in our dataset. Due to this, I need to impute data to fill null values

# Manual Pandas Data Imputing

In [22]:
# Get  Columns with Null values and split by datatype

for col in data.columns[data.isna().any()]:
    print(f'{col}: {data[col].dtypes}')

Student ID: float64
Age: float64
Gender: str
Height: float64
Weight: float64
Blood Type: str
BMI: float64
Temperature: float64
Heart Rate: float64
Blood Pressure: float64
Cholesterol: float64
Diabetes: str
Smoking: str

In [23]:
# Replace numeric column with null values with the mean of that feature
data_copy = data.copy()

num_cols = ['Student ID', 'Age', 'Height', 'Weight', 'BMI', 'Temperature', 'Heart Rate', 'Blood Pressure', 'Cholesterol']

for col in num_cols:
    data_copy[col] = data_copy[col].fillna(data_copy[col].mean())

In [24]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  str
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  str
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  str
 12  Smoking         180000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB

In [25]:
data_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      200000 non-null  float64
 1   Age             200000 non-null  float64
 2   Gender          180000 non-null  str
 3   Height          200000 non-null  float64
 4   Weight          200000 non-null  float64
 5   Blood Type      180000 non-null  str
 6   BMI             200000 non-null  float64
 7   Temperature     200000 non-null  float64
 8   Heart Rate      200000 non-null  float64
 9   Blood Pressure  200000 non-null  float64
 10  Cholesterol     200000 non-null  float64
 11  Diabetes        180000 non-null  str
 12  Smoking         180000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB

In [29]:
cat_cols = ['Gender', 'Blood Type', 'Diabetes', 'Smoking']

for col in cat_cols:
    data_copy[col] = data_copy[col].fillna(data_copy[col].mode()[0])

In [30]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  str
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  str
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  str
 12  Smoking         180000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB

In [31]:
data_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      200000 non-null  float64
 1   Age             200000 non-null  float64
 2   Gender          200000 non-null  str
 3   Height          200000 non-null  float64
 4   Weight          200000 non-null  float64
 5   Blood Type      200000 non-null  str
 6   BMI             200000 non-null  float64
 7   Temperature     200000 non-null  float64
 8   Heart Rate      200000 non-null  float64
 9   Blood Pressure  200000 non-null  float64
 10  Cholesterol     200000 non-null  float64
 11  Diabetes        200000 non-null  str
 12  Smoking         200000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB

# Fill null values using scikit learn Imputer method

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

data_copy_2 = data.copy()

# Create a imputer object for numeric columns
# strategy tells the imputer how to fill null values (mean for numeric)
# missing_values tells the imputer what values to fill (np.nan / null values)
num_imputer = SimpleImputer(strategy='mean', missing_values=np.nan) 

for col in num_cols:
    num_imputer.fit(data_copy_2[[col]])
    data_copy_2[col] = num_imputer.transform(data_copy_2[[col]])

In [35]:
data_copy_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      200000 non-null  float64
 1   Age             200000 non-null  float64
 2   Gender          180000 non-null  str
 3   Height          200000 non-null  float64
 4   Weight          200000 non-null  float64
 5   Blood Type      180000 non-null  str
 6   BMI             200000 non-null  float64
 7   Temperature     200000 non-null  float64
 8   Heart Rate      200000 non-null  float64
 9   Blood Pressure  200000 non-null  float64
 10  Cholesterol     200000 non-null  float64
 11  Diabetes        180000 non-null  str
 12  Smoking         180000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB

In [39]:
# Create a string Imputer object

# strategy for this string Imputer is most_frequent
# missing_values is still np.nan values
str_imputer = SimpleImputer(strategy='most_frequent', missing_values=np.nan)

for col in cat_cols:
    str_imputer.fit(data_copy_2[[col]])

    # For string/categorical columns, we need to use ravel() to bring back to a vector (dont need to for num cols)
    data_copy_2[col] = str_imputer.transform(data_copy_2[[col]]).ravel()

In [40]:
data_copy_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      200000 non-null  float64
 1   Age             200000 non-null  float64
 2   Gender          200000 non-null  str
 3   Height          200000 non-null  float64
 4   Weight          200000 non-null  float64
 5   Blood Type      200000 non-null  str
 6   BMI             200000 non-null  float64
 7   Temperature     200000 non-null  float64
 8   Heart Rate      200000 non-null  float64
 9   Blood Pressure  200000 non-null  float64
 10  Cholesterol     200000 non-null  float64
 11  Diabetes        200000 non-null  str
 12  Smoking         200000 non-null  str
dtypes: float64(9), str(4)
memory usage: 19.8 MB